//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QueDatabaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class Que
    {
        public int Id { get; set; }
        public int TransactionId { get; set; }
        public bool Priority { get; set; }
        public int Status { get; set; }
        public string TicketCode { get; set; }
        public Nullable<int> CounterId { get; set; }
    
        public virtual Counter Counter { get; set; }
        public virtual Transaction Transaction { get; set; }
    }
}
